=== sergyanlaszlo/JDBXZ1_XMLGyak/SL_erToXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="sema">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="A">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Ac">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Acd"/>
                                    <xs:element name="Ace"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="Aa" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="B">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Bb">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Bbx"/>
                                    <xs:element name="Bby"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="Ba" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="C">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Cb"/>
                    </xs:sequence>
                    <xs:attribute name="Ca" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="A_B">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="A_Bc"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== sergyanlaszlo/JDBXZ1_XMLGyak/SL_XSDtoXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<sema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SL_erToXSD.xsd">
    <A Aa="ACSA">
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>
    <B Ba="YCVA">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>
    <C Ca="ADS">
        <Cb></Cb>
    </C>
    <A_B>
        <A_Bc></A_Bc>
    </A_B>
</sema><?xml version="1.0" encoding="UTF-8"?>
<sema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SL_erToXSD.xsd">
    <A Aa="ACSA">
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>
    <B Ba="YCVA">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>
    <C Ca="ADS">
        <Cb></Cb>
    </C>
    <A_B>
        <A_Bc></A_Bc>
    </A_B>
</sema>
